version: '3'
services:
  app:
    container_name: dockerized-react-ui
    stdin_open: true
    command:  yarn web:start
    build:
      context: ""
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/packages/react-ui/node_modules'
    ports:
      - '3000:3001'
    environment:
      - NODE_ENV=development
      - CI=true
