language: node_js
node_js:
  - 14
install:
  - yarn
script:
  - yarn eslint:fix
  - yarn storybook:build
  - yarn build:docs:html
  - yarn coveralls
  - yarn web:firebase:deploy

notifications:
  email:
    recipients:
      - well.oliveira.snt@gmail.com.br
    on_success: never
    on_failure: always
