language: node_js
node_js:
  - 14
script:
  - yarn eslint:fix
  - yarn storybook:build
  - yarn build:docs:html
  - yarn coveralls

cache:
  yarn: true
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - well.oliveira.snt@gmail.com.br
    on_success: always # default: change
    on_failure: always # default: always
